# Generated by Django 3.2.13 on 2023-01-20 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateCrate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
